spring.datasource.url=jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.cadzmstoqlswcxifuluj
spring.datasource.password=shutthefuckupbitch
server.port=4200


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=ab3ca3001@smtp-brevo.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=elouedwassim@gmail.com
app.frontend.url=http://localhost:3000


jwt.secret=openssl rand -base64 32
jwt.expiration=86400000
jwt.refresh-expiration=604800000


spring.mail.password=xsmtpsib-57f16ee55aae2196c5b9d8ba2c57f26cfcf4e88fd329b6cf17b1eeb07d652fdc-5QOxRPDCEn1uVvmo

