spring.datasource.url=jdbc:postgresql://localhost:5432/wym
spring.datasource.username=postgres
spring.datasource.password=1337
server.port=4200
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
